### PR TITLE
feat: animate speaker pages on scroll

### PR DESCRIPTION
**Pull request by zax-xyz**
thoughts?

https://user-images.githubusercontent.com/25019123/194860012-c9db6a16-d787-4c5f-9ebf-45f6b108e59a.mp4

### CODE REVIEW

**Comment by Varun-Sethu** [comment]
thoughts: very epic, very cool 😎

**Review by zax-xyz — COMMENTED** [review]
wow this is epic

**Comment by zax-xyz** [comment]
> wow this is epic

omg ty

**Comment by Varun-Sethu** [comment]
> > wow this is epic
> 
> omg ty

you're welcome

**Pull request merged**
